import { safetyLabels, effectiveSafety, recipeSteps } from './model.mjs';
export const escape = value => String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
export function safetyBadge(s) {const safety=effectiveSafety(s);return `<span class="badge ${safety}">${safetyLabels[safety]}</span>`;}
const action=(name,s)=>`data-action="${name}" data-id="${escape(s.id)}"`;
export const favoriteButton=s=>`<button class="favorite" ${action('favorite',s)} aria-label="${s.favorite?'Quitar de':'Agregar a'} favoritos: ${escape(s.name)}" aria-pressed="${s.favorite}">${s.favorite?'★':'☆'}</button>`;
export function card(s) {
  const steps=recipeSteps(s);
  const preview=s.type==='recipe'?steps.slice(0,2).join('\n')+(steps.length>2?`\n… ${steps.length} pasos`:''):s.command;
  return `<article class="snippet-card"><button class="card-open" ${action('detail',s)} aria-haspopup="dialog" aria-label="Ver detalle: ${escape(s.name)}"><h3>${escape(s.name)}</h3><div class="card-meta"><span>${escape(s.technology)}</span><span class="badge type-badge">${s.type==='recipe'?'RECETA':'COMANDO'}</span>${safetyBadge(s)}</div><pre>${escape(preview)}</pre></button><div class="card-bottom"><div class="tags">${s.tags.slice(0,3).map(tag=>`<span class="tag">${escape(tag)}</span>`).join('')}</div><button ${action('copy',s)} aria-label="${s.type==='recipe'?'Copiar receta':'Copiar comando'}: ${escape(s.name)}">${effectiveSafety(s)==='destructive'?'Revisar y copiar':'Copiar'}</button>${favoriteButton(s)}</div></article>`;
}
export function frequentCard(s){return `<div class="frequent-item"><button class="frequent-open" ${action('detail',s)} aria-haspopup="dialog"><small>${s.type==='recipe'?'RECETA · ':''}${escape(s.name)}</small><code>${escape(s.command.split('\n')[0])}</code></button><button ${action('copy',s)} aria-label="Copiar: ${escape(s.name)}">${effectiveSafety(s)==='destructive'?'Revisar':'Copiar'}</button></div>`;}
export function detail(s) {
  const block=s.type==='recipe'?recipeSteps(s).map((cmd,index)=>`<div class="recipe-step"><span class="step-number">${String(index+1).padStart(2,'0')}</span><code>${escape(cmd)}</code><button ${action('copy-step',s)} data-step="${index}" aria-label="Copiar paso ${index+1}">Copiar</button></div>`).join(''):`<pre>${escape(s.command)}</pre>`;
  return `<h2 id="detail-name" class="detail-title">${escape(s.name)}</h2><div class="detail-meta"><span>${escape(s.technology)}</span><span class="badge type-badge">${s.type==='recipe'?'RECETA':'COMANDO'}</span>${safetyBadge(s)}</div><div class="command-block">${block}</div>${s.type==='recipe'?'<p class="field-help">Ejecuta cada paso por separado y revisa su resultado antes de continuar.</p>':''}<section class="detail-section"><h3>¿Qué hace?</h3><p>${escape(s.description)}</p></section><section class="detail-section"><h3>¿Cuándo usarlo?</h3><ul>${s.useCases.map(text=>`<li>${escape(text)}</li>`).join('')}</ul></section><dl class="detail-facts"><div><dt>Plataforma</dt><dd>${escape(s.platform)}</dd></div><div><dt>Seguridad</dt><dd>${safetyLabels[effectiveSafety(s)]}</dd></div><div><dt>Uso local</dt><dd>${s.usageCount} copia${s.usageCount===1?'':'s'}</dd></div></dl><div class="tags">${s.tags.map(tag=>`<span class="tag">${escape(tag)}</span>`).join('')}</div><div class="detail-section detail-actions"><button class="primary" ${action('copy',s)}>${s.type==='recipe'?'Copiar todo':'Copiar comando'}</button>${favoriteButton(s)}<button ${action('edit',s)}>${s.custom?'Editar':'Personalizar'}</button><button ${action('delete',s)}>Eliminar</button></div>${s.custom?'':'<p class="field-help">Incluido en Snippets. Personalizar guarda una copia editable; puedes restaurar los incluidos desde Biblioteca.</p>'}`;
}
