import test from 'node:test';
import assert from 'node:assert/strict';
import {measure,mergeSegments,SpeechTracker,makeTimeMap,validateTimeMap,outputToOriginal,originalToOutput,chooseChannel,gainFor,VoiceDSP,limit,pcm16,wavHeader,longAudioPlan,resample,safeMix,settingsFor} from '../core.mjs';
import {validateHandoff,HANDOFF_KIND,receiveAudioHandoff,sendAudioHandoff} from '../../shared/audio-handoff.mjs';
import {validRecovery} from '../recovery.mjs';
import {openReader} from '../reader.mjs';

test('context preserves starts/ends and merges nearby speech without exceeding source',()=>{assert.deepEqual(mergeSegments([{start:.1,end:2,confidence:.8},{start:2.5,end:3,confidence:.7},{start:8,end:10,confidence:.9}],10),[{start:0,end:3.65,confidence:.8},{start:7.65,end:10,confidence:.9}]);});
test('VAD uses hysteresis and retains short words; probabilities, not loudness, trigger speech',()=>{const t=new SpeechTracker();for(let i=0;i<4;i++)t.push(.9,i*.032,(i+1)*.032);for(let i=4;i<30;i++)t.push(.05,i*.032,(i+1)*.032);assert.equal(t.finish().length,1);assert.equal(t.segments[0].start,0);assert.equal(t.segments[0].end,.128);});
test('balanced silence compression preserves short pauses and inserts .5 seconds for long gaps',()=>{const map=makeTimeMap([{start:2,end:4},{start:12,end:15}],20);assert.equal(validateTimeMap(map,20),5+2*.35+2*.65+1.5);assert.ok(map.some(s=>s.type==='pause'));assert.equal(outputToOriginal(map.find(s=>s.type==='speech').outputStart,map),1.65);});
test('no voice or disabled silence processing preserves all original audio',()=>{assert.equal(validateTimeMap(makeTimeMap([],3600),3600),3600);assert.equal(validateTimeMap(makeTimeMap([{start:10,end:20}],30,'off'),30),30);});
test('time conversion and boundaries are monotonic, exportable and invertible on retained spans',()=>{const map=makeTimeMap([{start:10,end:20},{start:60,end:70}],90);for(const s of map){const t=(s.outputStart+s.outputEnd)/2;assert.ok(Math.abs(originalToOutput(outputToOriginal(t,map),map)-t)<1e-6);}assert.equal(outputToOriginal(-100,map),0);assert.equal(outputToOriginal(999,map),90);assert.throws(()=>validateTimeMap([{outputStart:1,outputEnd:3,originalStart:0,originalEnd:2}]),/monotónico/);assert.throws(()=>validateTimeMap([{outputStart:0,outputEnd:3,originalStart:0,originalEnd:2}]),/monotónico/);assert.throws(()=>validateTimeMap([]));});
test('channel scoring rewards actual speech, penalizes clipping, and protects antiphase mixing',()=>{const c={speechEnergy:1,speechSamples:1000,noiseEnergy:.01,noiseSamples:1000,speechSeconds:10,clipped:0,samples:1000};assert.equal(chooseChannel([c,{...c,speechSeconds:50}]),1);const a=new Float32Array([.3,-.3,.5]),b=a.map(v=>-v);assert.deepEqual(safeMix([a,b]),a);assert.deepEqual(safeMix([a,a]),a);});
test('RMS/clipping detection and limited gain do not claim LUFS',()=>{const s=measure(new Float32Array([1,-1,0,0]));assert.equal(s.clipped,2);assert.equal(s.peak,1);assert.equal(s.rms,Math.sqrt(.5));assert.equal(gainFor(.00001),12.59);assert.ok(gainFor(.5)<1);assert.equal(limit(NaN),0);});
test('gain/compression state survives blocks and never clips',()=>{const dsp=new VoiceDSP(settingsFor('balanced',{denoise:false}));for(const amplitude of [.001,.01,.8,1.5]){const input=Float32Array.from({length:16000},(_,i)=>amplitude*Math.sin(i*.1));const out=dsp.process(input);assert.ok(measure(out).peak<=.89126);}const quiet=new VoiceDSP(settingsFor('fast'));const samples=new Float32Array(16000).fill(.001);assert.ok(measure(quiet.process(samples)).rms>.002);const noise=new VoiceDSP(settingsFor('fast'));assert.equal(measure(noise.process(samples,false)).rms,measure(samples).rms);});
test('PCM WAV has exact duration/header and edge fades prevent cut clicks',()=>{const input=new Float32Array(16000).fill(2),bytes=pcm16(input,true,true),header=wavHeader(input.length);assert.equal(new DataView(header.buffer).getUint32(40,true),32000);assert.equal(new DataView(bytes.buffer).getInt16(0,true),0);assert.equal(new DataView(bytes.buffer).getInt16(bytes.length-2,true),0);assert.ok(new DataView(bytes.buffer).getInt16(200,true)<=29205);});
test('resampler filters aliasing and preserves duration',()=>{const input=Float32Array.from({length:48000},(_,i)=>Math.sin(i*2*Math.PI*12000/48000));const out=resample(input,48000);assert.equal(out.length,16000);assert.ok(measure(out.subarray(50,-50)).rms<.005);const tone=Float32Array.from({length:48000},(_,i)=>Math.sin(i*2*Math.PI*1000/48000));assert.ok(measure(resample(tone,48000)).rms>.65);});
test('an hour plan uses 360 bounded slabs; memory bound does not scale with duration',()=>{assert.equal(longAudioPlan(3600).blocks,360);assert.equal(longAudioPlan(3600).outputBytes,115200044);assert.equal(longAudioPlan(30).maxPcmSamples,longAudioPlan(3600).maxPcmSamples);});
test('handoff validates version, token, WAV size, and original timeline; stale or malformed rejected',()=>{const file=new Blob([wavHeader(16000),new Uint8Array(32000)],{type:'audio/wav'}),p={kind:HANDOFF_KIND,version:1,token:'test',file,name:'junta.wav',originalDuration:2,timeMap:[{outputStart:0,outputEnd:1,originalStart:1,originalEnd:2}]};assert.equal(validateHandoff(p,'test').file.name,'junta.wav');for(const bad of [{...p,version:2},{...p,token:'wrong'},{...p,file:new Blob()},{...p,timeMap:[{outputStart:0,outputEnd:2,originalStart:0,originalEnd:2}]}])assert.throws(()=>validateHandoff(bad,'test'));});
test('blocked popup provides fallback without discarding prepared WAV',()=>{const messages=[],browser={location:{href:'https://example.com/audio/'},open:()=>null};sendAudioHandoff({}, {browser,onStatus:s=>messages.push(s)});assert.match(messages[0],/Descarga el WAV/);});
test('recovery contract stores only small metadata and requires versioned identity',()=>{assert.equal(validRecovery({version:1,identity:'sha',analysis:{duration:60,channelStats:[{segments:[],peaks:[]}]}}),true);assert.equal(Boolean(validRecovery({version:2})),false);});
test('Pages real reader seeks across an hour of stereo PCM without ever reading whole file',async()=>{
  // Sparse zeros backed by Blob pieces, never another hour-long Float32Array.
  const seconds=3600,rate=16000,header=wavHeader(seconds*rate),h=new DataView(header.buffer);h.setUint16(22,2,true);h.setUint32(28,rate*4,true);h.setUint16(32,4,true);h.setUint32(40,seconds*rate*4,true);h.setUint32(4,36+seconds*rate*4,true);
  const slab=new Uint8Array(rate*10*4),v=new DataView(slab.buffer);for(let i=0;i<rate*10;i++){v.setInt16(i*4,2000,true);v.setInt16(i*4+2,-2000,true);}const file=new File([header,...new Array(360).fill(slab)],'hour.wav',{type:'audio/wav'});file.arrayBuffer=()=>{throw new Error('Whole-file decode forbidden');};const source=await openReader(file);try{assert.equal(source.channels,2);assert.equal(source.duration,seconds);for(const t of [0,1790,3590]){const planes=await source.read(t,t+10);assert.equal(planes[0].length,160000);assert.ok(planes[0][100]>.06);assert.ok(planes[1][100]<-.06);}await assert.rejects(()=>source.read(0,3600),/Bloque/);}finally{source.dispose();}
});
