import {settingsFor,db,outputToOriginal,originalToOutput} from './core.mjs';
import {removeTemp,cleanupTemps} from './output.mjs';
import {openTabSession} from './tab-session.mjs';
import {readRecovery,saveRecovery,deleteRecovery,validRecovery} from './recovery.mjs';
import {sendAudioHandoff} from '../shared/audio-handoff.mjs';
let sessionScope=crypto.randomUUID(),tabSession=null;const scopeReady=openTabSession().then(session=>{tabSession=session;sessionScope=session.scope;return cleanupTemps([],sessionScope);});
const $=id=>document.getElementById(id),clock=s=>{s=Math.max(0,Math.round(s||0));return (s>=3600?String(Math.floor(s/3600)).padStart(2,'0')+':':'')+String(Math.floor(s/60)%60).padStart(2,'0')+':'+String(s%60).padStart(2,'0');};
let file=null,sourceUrl=null,analysis=null,identity=null,result=null,previewResult=null,worker=null,busy=false,consentPending=false,workerTemp=null,queued=null,saved=null,wakeLock=null,view='original',selection=null,handoffCleanup=null,abClean=false,abActive=false,loading=false;
function status(text,error=false){$('status').textContent=text;$('status').classList.toggle('error',error);}
function settings(){return settingsFor($('preset').value,{channel:$('channel').value,silence:$('silence').value,denoise:$('denoise').checked,intensity:Number($('intensity').value),highpass:$('highpass').checked,normalize:$('normalize').checked,compress:$('compress').checked});}
function buttons(){const locked=busy||consentPending||loading;for(const id of ['dropzone','remove','preset','channel','silence','denoise','intensity','highpass','normalize','compress','save','restore','forget'])$(id).disabled=locked;$('analyze').disabled=!file||locked;$('prepare').disabled=!analysis||locked;$('preview').disabled=!analysis||locked;$('cancel').hidden=!busy;$('ab').disabled=!previewResult||locked;$('original-mode').disabled=!file;$('clean-mode').disabled=!result;$('handoff').disabled=!result||locked;$('file-input').disabled=locked;}
function consent(title,text,engines,onApprove){if(consentPending)return Promise.resolve(false);consentPending=true;buttons();$('consent-title').textContent=title;$('consent-text').textContent=text;$('consent-engines').textContent=engines;$('consent').returnValue='';return new Promise(resolve=>{const dialog=$('consent');$('approve').onclick=()=>{if(onApprove)onApprove();};dialog.addEventListener('close',()=>{consentPending=false;$('approve').onclick=null;buttons();resolve(dialog.returnValue==='approve');},{once:true});dialog.showModal();});}
function metrics(target,entries){target.replaceChildren();for(const [name,value]of entries){const div=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=name;dd.textContent=value;div.append(dt,dd);target.append(div);}}
function renderAnalysis(){if(!analysis)return;const c=analysis.channelStats[analysis.recommended];$('diagnosis-title').textContent='La grabación, en números.';$('recommendation').textContent=c.segments.length?`${c.rms<.04?'Voz baja. ':''}${analysis.duration-c.speechSeconds>analysis.duration*.2?'Hay pausas / no voz para revisar. ':''}Recomendamos Preparar junta y probar un fragmento antes.`:'Silero no encontró voz con suficiente confianza. Conservaremos todo el audio; escucha el original y prueba otro canal.';
metrics($('diagnosis'),[['Duración',clock(analysis.duration)],['Formato',(file.name.split('.').pop()||'Audio').toUpperCase()+' / '+analysis.codec.toUpperCase()],['Canales',analysis.channels===1?'Mono':analysis.channels+' canales'],['Frecuencia',(analysis.rate/1000).toFixed(1)+' kHz'],['Nivel RMS',db(c.rms).toFixed(1)+' dBFS'],['Pico',db(c.peak).toFixed(1)+' dBFS'],['Clipping',c.clipped?'Sí · '+(c.clipped/c.samples*100).toFixed(3)+'%':'No detectado'],['Voz detectada',clock(c.speechSeconds)],['Silencio / no voz',clock(analysis.duration-c.speechSeconds)],['Ruido orientativo',c.noiseSamples?c.noiseDb.toFixed(1)+' dBFS':'No estimable'],['Canal recomendado',analysis.channels===1?'Mono':analysis.recommended===0?'Izquierdo':analysis.recommended===1?'Derecho':'Canal '+(analysis.recommended+1)]]);
$('channel-detail').replaceChildren();analysis.channelStats.forEach((ch,i)=>{const p=document.createElement('p');p.textContent=`Canal ${i+1}: voz ${clock(ch.speechSeconds)} · RMS ${db(ch.rms).toFixed(1)} dBFS · ${ch.clipped?'con clipping':'sin clipping'} · ${ch.segments.length} segmentos. El ruido orientativo usa el percentil 15 del RMS; puede incluir voz suave.`;$('channel-detail').append(p);});draw();}
async function requestWake(){if(!$('wake').checked||!busy||!navigator.wakeLock||document.visibilityState!=='visible')return;try{wakeLock=await navigator.wakeLock.request('screen');wakeLock.addEventListener('release',()=>{wakeLock=null;});}catch{status('El dispositivo no permite mantener la pantalla activa. Puedes continuar.');}}
async function finish(){busy=false;worker?.terminate();worker=null;queued=null;workerTemp=null;await wakeLock?.release().catch(()=>{});wakeLock=null;buttons();}
async function error(error){$('error-details').hidden=false;$('technical').textContent=error.message||String(error);status(error.name==='QuotaExceededError'?'No queda espacio para el WAV temporal. Tu fuente sigue intacta. Libera espacio o prueba un fragmento.':'No se pudo completar el proceso. Tu audio sigue intacto. Prueba Rápido, otro navegador o WAV PCM.',true);const temp=workerTemp;await finish();await removeTemp(temp);}
async function storeAnalysis(){if(!$('save').checked||!analysis||!identity)return;try{saved={version:1,identity,name:file.name,settings:settings(),analysis};await saveRecovery(saved);renderRecovery();}catch{status('Análisis listo, pero no se pudo guardar la recuperación. Descarga el análisis si lo necesitas.');}}
function makeWorker(){worker=new Worker(new URL('./worker.mjs?v=1.0.0',import.meta.url),{type:'module'});worker.onerror=e=>{error(new Error(e.message||'El Worker falló.'));};worker.onmessage=async({data})=>{
  if(data.type==='metadata'){$('file-info').textContent=`${clock(data.metadata.duration)} · ${data.metadata.channels} canales · ${(file.size/1048576).toFixed(1)} MB`;}
  if(data.type==='progress'){$('progress-box').hidden=false;$('stage').textContent=data.stage;$('progress').value=data.percent;$('percent').textContent=Math.round(data.percent)+'%';$('progress-meta').textContent=`${clock(data.completed)} / ${clock(data.duration)} analizados${data.segments!==undefined?' · '+data.segments+' segmentos':''}${data.resultDuration?' · resultado previsto '+clock(data.resultDuration):''}`;}
  if(data.type==='tempfile')workerTemp=data.name;
  if(data.type==='warning')status(data.message);
  if(data.type==='analysis'){analysis=data.analysis;identity=data.identity||identity;renderAnalysis();if(data.restored&&queued){const next=queued;queued=null;worker.postMessage(next);return;}await storeAnalysis();status(data.restored?'Análisis recuperado y archivo verificado.':'Análisis completo. Prueba un fragmento o pulsa Preparar junta.');await finish();}
  if(data.type==='result'){await releaseResult(result);result={...data,url:URL.createObjectURL(data.blob)};renderResult();status(data.metrics.warnings.length?data.metrics.warnings.join(' '):'Junta preparada. Escucha el WAV antes de enviarlo a Transcribe.');await finish();}
  if(data.type==='preview'){await releaseResult(previewResult);previewResult={...data,url:URL.createObjectURL(data.blob)};abClean=false;abActive=false;$('ab').textContent='A/B · escuchar';$('preview-note').textContent=`Fragmento ${clock(data.timeMap[0].originalStart)}–${clock(data.timeMap[0].originalEnd)}. A/B alterna el mismo punto del original y el procesado. Sin recortar pausas.`;status('Vista previa lista. Pulsa A/B para comparar.');await finish();}
  if(data.type==='error'){const mp3=data.mp3;await error(data);if(mp3)status('Este navegador necesita el lector MP3 adicional. Pulsa Analizar voz y autorízalo.',true);}
};return worker;}
async function beginAnalyze(restore=false){if(!file||busy||consentPending)return;const approved=await consent(restore?'Recuperar análisis.':'Analizar esta grabación.',restore?'Selecciona el mismo archivo original. Verificamos su SHA-256 completo por bloques antes de usar el análisis guardado.':'Revisamos todos los canales y detectamos habla por bloques. La grabación permanece en tu dispositivo. No se modifica el original.','Descarga local: lector ~0.5 MB, Silero V5 ~2.3 MB, ONNX CPU/WASM ~11.5 MB; el navegador puede reutilizar caché. MP3 WASM adicional ~0.16 MB si hace falta.');if(!approved)return;busy=true;buttons();$('error-details').hidden=true;await requestWake();await scopeReady;if(!busy)return;const w=makeWorker();w.postMessage({type:restore?'restore':'open',file,scope:sessionScope,allowMp3:true,settings:settings(),analysis:restore?saved.analysis:undefined,identity:restore?saved.identity:undefined});}
async function beginProcess(preview=false){if(!analysis||busy||consentPending)return;const s=settings();const start=Math.min(Math.max(0,Number($('preview-start').value)||0),Math.max(0,analysis.duration-.05)),end=Math.min(analysis.duration,start+Number($('preview-length').value));if(preview&&end-start<.05)return status('Selecciona un fragmento de al menos 0.05 segundos.',true);
const approved=await consent(preview?'Probar antes de preparar.':'Preparar junta.',preview?`Procesamos ${clock(start)}–${clock(end)} sin recortar pausas para comparar A/B.`:`Volvemos a leer por bloques: ${clock(analysis.duration)}. Conservamos 350 ms antes y 650 ms después del habla; comprimimos pausas según tu ajuste. WAV mono / 16 kHz con limitador.`,s.denoise?'RNNoise local ~4.7 MB con WASM integrado. Normalización RMS y compresión, sin prometer LUFS. Guarda el WAV temporal solo para esta sesión.':'Sin descarga RNNoise. Nivelado local según tus ajustes; el limitador siempre protege picos.');if(!approved)return;busy=true;buttons();$('error-details').hidden=true;await requestWake();await scopeReady;if(!busy)return;queued={type:preview?'preview':'prepare',settings:s,range:preview?{start,end}:undefined};const w=makeWorker();w.postMessage({type:'restore',file,scope:sessionScope,analysis,identity,allowMp3:true});}
async function releaseResult(r){if(!r)return;URL.revokeObjectURL(r.url);await removeTemp(r.tempName);}
async function cancel(){if(!busy)return;const temp=workerTemp;await finish();await removeTemp(temp);$('progress-box').hidden=true;status('Proceso cancelado. Worker, modelos y lector liberados. La fuente y el último resultado siguen disponibles.');}
async function acceptFile(candidate){if(busy||consentPending||loading||!candidate)return;if(!candidate.size||candidate.size>2*1024**3)return status('Elige un archivo con contenido de hasta 2 GB.',true);if(!/^(audio|video)\//.test(candidate.type)&&! /\.(m4a|aac|mp3|wav|flac|ogg|opus|webm|mov|mp4)$/i.test(candidate.name))return status('Elige audio o un video con pista de audio.',true);loading=true;buttons();await clearFile();loading=false;file=candidate;sourceUrl=URL.createObjectURL(file);$('player').src=sourceUrl;$('file-card').hidden=false;$('file-name').textContent=file.name;$('file-info').textContent=(file.size/1048576).toFixed(1)+' MB';buttons();status('Archivo listo. Autoriza el análisis para detectar voz.');beginAnalyze();}
async function clearFile(){handoffCleanup?.();handoffCleanup=null;$('player').pause();$('player').removeAttribute('src');$('player').load();if(sourceUrl)URL.revokeObjectURL(sourceUrl);sourceUrl=null;abActive=false;abClean=false;$('ab').textContent='A/B · escuchar';await releaseResult(result);await releaseResult(previewResult);file=null;analysis=null;identity=null;result=null;previewResult=null;selection=null;view='original';$('result-panel').hidden=true;$('file-card').hidden=true;$('progress-box').hidden=true;$('preview-note').textContent='';$('file-input').value='';$('diagnosis').replaceChildren();$('channel-detail').replaceChildren();$('recommendation').textContent='El análisis identifica voz con Silero y revisa cada canal.';$('diagnosis-title').textContent='Primero, escuchar.';buttons();draw();}
function renderResult(){const m=result.metrics;$('result-panel').hidden=false;$('result-title').textContent='Lista para Transcribe.';metrics($('result-metrics'),[['Original',clock(m.originalDuration)],['Voz detectada',clock(analysis.channelStats[analysis.recommended].speechSeconds)],['Procesado',clock(m.outputDuration)],['Reducción',((1-m.outputDuration/m.originalDuration)*100).toFixed(1)+'%'],['Pausas comprimidas',clock(Math.max(0,m.removed))],['Pico antes',db(m.inputPeak).toFixed(1)+' dBFS'],['Pico después',db(m.outputPeak).toFixed(1)+' dBFS'],['Canal',m.channel],['Ruido',m.denoise?'RNNoise activado':'Desactivado'],['Salida',(result.blob.size/1048576).toFixed(1)+' MB']]);drawWave($('result-waveform'),result.peaks,[],result.timeMap,m.outputDuration,0,m.outputDuration);buttons();draw();}
function viewData(){const clean=view==='clean'&&result;return {duration:clean?result.metrics.outputDuration:analysis?.duration||0,peaks:clean?result.peaks:analysis?.channelStats[analysis.recommended]?.peaks||[],speech:clean?result.timeMap.filter(s=>s.type==='speech').map(s=>({start:s.outputStart,end:s.outputEnd})):analysis?.channelStats[analysis.recommended]?.segments||[],map:result?.timeMap||[],clean};}
function drawWave(canvas,peaks,speech,map,duration,start,end,clean=true){const context=canvas.getContext('2d'),w=canvas.width,h=canvas.height;context.clearRect(0,0,w,h);if(!(duration>0&&end>start))return;const scale=w/(end-start);let max=.015;for(const p of peaks)max=Math.max(max,p.peak);for(const s of speech){const left=(s.start-start)*scale,right=(s.end-start)*scale;context.fillStyle='#bce5d217';context.fillRect(left,0,right-left,h);}context.strokeStyle='#9aabc1';context.lineWidth=1;const bins=new Float32Array(w),rmsBins=new Float32Array(w);for(const p of peaks){const x=Math.floor((p.time-start)*scale);if(x>=0&&x<w){bins[x]=Math.max(bins[x],p.peak);rmsBins[x]=Math.max(rmsBins[x],p.rms);}}context.beginPath();for(let x=0;x<w;x++){context.moveTo(x,h/2-bins[x]/max*h*.42);context.lineTo(x,h/2+bins[x]/max*h*.42);}context.stroke();context.strokeStyle='#e0be92';context.beginPath();let noiseIndex=0;for(let x=0;x<w;x++){const t=start+x/scale;while(noiseIndex<speech.length&&speech[noiseIndex].end<t)noiseIndex++;const voiced=speech[noiseIndex]&&t>=speech[noiseIndex].start&&t<=speech[noiseIndex].end;if(!voiced&&rmsBins[x]>.0005){context.moveTo(x,h/2-bins[x]/max*h*.42);context.lineTo(x,h/2+bins[x]/max*h*.42);}}context.stroke();context.strokeStyle='#bce5d2';context.beginPath();let speechIndex=0;for(let x=0;x<w;x++){const t=start+x/scale;while(speechIndex<speech.length&&speech[speechIndex].end<t)speechIndex++;if(speech[speechIndex]&&t>=speech[speechIndex].start&&t<=speech[speechIndex].end){context.moveTo(x,h/2-bins[x]/max*h*.42);context.lineTo(x,h/2+bins[x]/max*h*.42);}}context.stroke();context.strokeStyle='#f5ba87';for(let i=1;i<map.length;i++)if(map[i].originalStart-map[i-1].originalEnd>.001){const x=((clean?map[i].outputStart:map[i].originalStart)-start)*scale;context.beginPath();context.moveTo(x,0);context.lineTo(x,h);context.stroke();}if(selection&&canvas.id==='waveform'){context.fillStyle='#c3d8fa33';context.fillRect((selection.start-start)*scale,0,(selection.end-selection.start)*scale,h);}if(canvas.id==='waveform'){const cursor=abActive&&abClean?previewResult.timeMap[0].originalStart+$('player').currentTime:$('player').currentTime;const x=(cursor-start)*scale;context.strokeStyle='#f5f7fb';context.beginPath();context.moveTo(x,0);context.lineTo(x,h);context.stroke();}}
function viewport(){const data=viewData(),window=data.duration/Number($('zoom').value),start=Number($('viewport').value)/1000*Math.max(0,data.duration-window);return {...data,start,end:start+window};}
function draw(){const d=viewport();drawWave($('waveform'),d.peaks,d.speech,d.map,d.duration,d.start,d.end,d.clean);$('viewport').disabled=$('zoom').value==='1';}
function changeView(next){if(!file||(next==='clean'&&!result))return;const player=$('player'),old=player.currentTime||0,original=view==='clean'&&result?outputToOriginal(old,result.timeMap):old,playing=!player.paused;view=next;selection=null;abClean=false;abActive=false;$('ab').textContent='A/B · escuchar';player.src=next==='clean'?result.url:sourceUrl;player.currentTime=next==='clean'?originalToOutput(original,result.timeMap):original;$('original-mode').setAttribute('aria-pressed',String(next==='original'));$('clean-mode').setAttribute('aria-pressed',String(next==='clean'));if(playing)player.play().catch(()=>{});draw();}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function basename(){return(file.name.replace(/\.[^.]+$/,'').replace(/[^\p{L}\p{N}._-]+/gu,'-').slice(0,170)||'junta');}
const json=(data,name)=>download(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),basename()+'-'+name+'.json');
function renderRecovery(){if(!validRecovery(saved)){$('recovery-box').hidden=true;return;}$('recovery-box').hidden=false;$('recovery-info').textContent=`Análisis guardado: ${saved.name} · ${clock(saved.analysis.duration)}. Selecciona el original para verificarlo. No se guardó el audio.`;}
$('dropzone').onclick=()=>$('file-input').click();$('file-input').onchange=e=>acceptFile(e.target.files[0]);$('remove').onclick=async()=>{await clearFile();status('Carga una grabación para empezar.');};$('analyze').onclick=()=>beginAnalyze();$('prepare').onclick=()=>beginProcess();$('preview').onclick=()=>beginProcess(true);$('cancel').onclick=cancel;
for(const event of ['dragenter','dragover','dragleave','drop'])$('dropzone').addEventListener(event,e=>{e.preventDefault();$('dropzone').classList.toggle('dragover',['dragenter','dragover'].includes(event)&&!busy);if(event==='drop')acceptFile(e.dataTransfer.files[0]);});window.addEventListener('dragover',e=>{if([...e.dataTransfer.types].includes('Files'))e.preventDefault();});window.addEventListener('drop',e=>{e.preventDefault();if(!e.target.closest('#dropzone'))acceptFile(e.dataTransfer.files[0]);});document.addEventListener('paste',e=>{const f=e.clipboardData?.files[0];if(f){e.preventDefault();acceptFile(f);}});
$('preset').onchange=()=>{const s=settingsFor($('preset').value);for(const id of ['denoise','highpass','normalize','compress'])$(id).checked=s[id];$('intensity').value=$('preset').value==='quality'?.85:.65;status('Ajustes actualizados. Prueba el mismo fragmento A/B para elegir intensidad.');};
$('original-mode').onclick=()=>changeView('original');$('clean-mode').onclick=()=>changeView('clean');$('zoom').onchange=draw;$('viewport').oninput=draw;$('player').addEventListener('timeupdate',()=>{$('timeline-time').textContent=clock($('player').currentTime);draw();});
let pointerStart=null;function pointerTime(e){const r=$('waveform').getBoundingClientRect(),d=viewport();return Math.max(0,Math.min(d.duration,d.start+(e.clientX-r.left)/r.width*(d.end-d.start)));}
$('waveform').onpointerdown=e=>{if(!analysis)return;pointerStart=pointerTime(e);$('waveform').setPointerCapture(e.pointerId);};$('waveform').onpointermove=e=>{if(pointerStart===null)return;const t=pointerTime(e);selection={start:Math.min(pointerStart,t),end:Math.max(pointerStart,t)};draw();};$('waveform').onpointerup=e=>{if(pointerStart===null)return;const t=pointerTime(e);if(Math.abs(t-pointerStart)<.2){$('player').currentTime=t;selection=null;}else{const first=Math.min(t,pointerStart),original=view==='clean'?outputToOriginal(first,result.timeMap):first;$('preview-start').value=original.toFixed(1);const length=Math.max(10,Math.min(30,Math.ceil(Math.abs(t-pointerStart)/10)*10));$('preview-length').value=String(length);status(`Fragmento seleccionado desde ${clock(original)} · ${length} segundos.`);}pointerStart=null;draw();};$('waveform').onpointercancel=()=>{pointerStart=null;};$('waveform').onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();$('player').currentTime=Math.max(0,Math.min(viewData().duration,$('player').currentTime+(e.key==='ArrowRight'?5:-5)));}};
$('ab').onclick=()=>{if(!previewResult)return;const player=$('player'),start=previewResult.timeMap[0].originalStart,end=previewResult.timeMap[0].originalEnd;const offset=abActive?(abClean?player.currentTime:Math.max(0,Math.min(end-start,player.currentTime-start))):0;abActive=true;view='original';abClean=!abClean;$('original-mode').setAttribute('aria-pressed','true');$('clean-mode').setAttribute('aria-pressed','false');player.src=abClean?previewResult.url:sourceUrl;player.currentTime=abClean?offset:start+offset;$('ab').textContent=abClean?'A/B · escuchando procesado':'A/B · escuchando original';player.play().catch(()=>status('Pulsa reproducir para escuchar.'));};$('player').addEventListener('timeupdate',()=>{if(previewResult&&abActive&&!abClean&&$('player').currentTime>=previewResult.timeMap[0].originalEnd&&$('ab').textContent.includes('escuchando original'))$('player').pause();});
$('download').onclick=()=>download(result.blob,basename()+'-clean.wav');$('map').onclick=()=>json({version:1,originalDuration:analysis.duration,outputDuration:result.metrics.outputDuration,timeMap:result.timeMap},'time-map');$('analysis-export').onclick=()=>json({version:1,name:file.name,identity,analysis,settings:result.settings,metrics:result.metrics},'analysis');$('segments-export').onclick=()=>{const segments=analysis.channelStats[analysis.recommended].segments;download(new Blob(['start,end,type,speaker,confidence\n'+segments.map(s=>`${s.start.toFixed(3)},${s.end.toFixed(3)},speech,,${s.confidence.toFixed(3)}`).join('\n')],{type:'text/csv'}),basename()+'-segments.csv');};
$('handoff').onclick=()=>consent('Enviar a Transcribe.','Autorizas compartir el WAV preparado y su mapa de tiempos con otra pestaña de Transcribe en este mismo origen. Transcribe crea por bloques su propia copia temporal local (requiere espacio disponible) para poder cerrar Audio Lab. No hay subida ni archivo permanente. Transcribe solicitará autorización antes de descargar Whisper.','Si las ventanas están bloqueadas, podrás descargar el WAV y abrir Transcribe manualmente.',()=>{handoffCleanup?.();$('handoff-status').textContent='Abriendo Transcribe…';handoffCleanup=sendAudioHandoff({file:result.blob,name:basename()+'-clean.wav',timeMap:result.timeMap,originalDuration:analysis.duration},{onStatus:text=>{$('handoff-status').textContent=text;}});});
$('wake').onchange=()=>{if($('wake').checked)requestWake();else{wakeLock?.release().catch(()=>{});wakeLock=null;}};document.addEventListener('visibilitychange',()=>{if(busy&&$('wake').checked&&document.visibilityState==='visible')requestWake();});
$('save').onchange=async()=>{if($('save').checked)await storeAnalysis();};$('restore').onclick=async()=>{if(!saved||!file)return status('Primero selecciona el archivo original; después recupera el análisis.',true);if(saved.settings){$('preset').value=saved.settings.preset;for(const id of ['channel','silence','intensity'])$(id).value=saved.settings[id];for(const id of ['denoise','highpass','normalize','compress'])$(id).checked=Boolean(saved.settings[id]);}beginAnalyze(true);};$('forget').onclick=async()=>{try{await deleteRecovery();saved=null;renderRecovery();status('Recuperación eliminada.');}catch{status('No se pudo borrar la recuperación.',true);}};
function capabilities(){const capabilities=[['WebAssembly',typeof WebAssembly==='object'],['Workers',typeof Worker==='function'],['AudioWorklet',typeof AudioWorkletNode==='function'],['WebGPU',Boolean(navigator.gpu)],['SharedArrayBuffer',typeof SharedArrayBuffer==='function'],['OfflineAudioContext',Boolean(window.OfflineAudioContext||window.webkitOfflineAudioContext)],['OPFS',Boolean(navigator.storage?.getDirectory)],['WebCodecs',typeof AudioDecoder==='function']];$('capabilities').textContent=capabilities.map(([k,v])=>k+': '+(v?'sí':'no')).join(' · ')+` · Hilos: ${navigator.hardwareConcurrency||'no informado'} · RAM: ${navigator.deviceMemory? navigator.deviceMemory+' GB':'no informada'}`;if(typeof Worker!=='function'||typeof WebAssembly!=='object'){$('dropzone').disabled=true;status('Necesitas un navegador con Workers y WebAssembly. Prueba Chrome, Edge o Safari actualizado.',true);}}
readRecovery().then(record=>{saved=validRecovery(record)?record:null;renderRecovery();}).catch(()=>{});buttons();capabilities();draw();
window.addEventListener('pagehide',()=>{tabSession?.close();worker?.terminate();wakeLock?.release().catch(()=>{});handoffCleanup?.();removeTemp(workerTemp);removeTemp(result?.tempName);removeTemp(previewResult?.tempName);});

if(typeof AudioDecoder==='function')Promise.all(['mp4a.40.2','mp3','opus','flac'].map(async codec=>{try{const r=await AudioDecoder.isConfigSupported({codec,sampleRate:48000,numberOfChannels:2});return codec+': '+(r.supported?'sí':'no');}catch{return codec+': no';}})).then(codecs=>{$('capabilities').textContent+=' · Códecs nativos: '+codecs.join(', ')+' · WAV PCM: lector local';});
