// Source of truth for routes, status, categories and future tool briefs.
export const categories = [
  { id:'daily', name:'Uso diario', description:'Lo que abres, usas y vuelves a abrir.' },
  { id:'data', name:'Datos', description:'Entender y preparar archivos antes de trabajar con ellos.' },
  { id:'development', name:'Desarrollo', description:'De una idea, un error o un archivo al siguiente paso.' },
  { id:'files', name:'Archivos', description:'Preparar media y documentos sin salir de tu flujo.' },
  { id:'utilities', name:'Utilidades', description:'Resolver lo pequeño en un momento.' },
  { id:'personal', name:'Personal', description:'Guardar lo que ya resolviste y encontrarlo después.' },
];

export const tools = [
  { id:'drop', name:'Drop', category:'daily', ready:true, daily:true, summary:'Texto y archivos, de una pantalla a otra.', purpose:'Transferir código, capturas, Excel y documentos entre tus dispositivos.', features:['Sala de cuatro números y QR','WebRTC y PeerJS','Pegado, PWA y sesión local'], examples:['Pasar una captura del iPad a la laptop.'], related:['transcribe','shot'] },
  { id:'transcribe', name:'Transcribe', category:'daily', ready:true, daily:true, summary:'De audio o captura a texto editable.', purpose:'Transcribir voz y extraer texto de imágenes en tu navegador.', features:['Whisper y OCR con Tesseract','Mejora para voz baja','Texto editable, TXT y SRT'], examples:['Convertir una grabación de junta en texto.'], related:['audio','drop','context'] },
  { id:'inspect', name:'Inspect', category:'data', daily:true, summary:'Conoce tus archivos antes de usarlos.', purpose:'Arrastrar XLSX, CSV, JSON o TXT y revisar su estructura y calidad para datasets, universidad y archivos de Visteon.', features:['Filas, columnas, headers y tipos de datos','Duplicados, celdas vacías y valores únicos','Encoding, vista previa y calidad de datos'], examples:['Revisar cuántas piezas únicas tiene un Excel de inventario.','Detectar columnas vacías o nombres de headers diferentes.'], related:['clean','diff','drop'] },
  { id:'diff', name:'Diff', category:'data', daily:true, summary:'Qué cambió entre el archivo A y el B.', purpose:'Comparar versiones de texto, código, CSV, JSON y Excel, con diferencias fáciles de revisar.', features:['Contenido agregado, eliminado y modificado','Estadísticas de cambios','Diferencias visuales entre dos versiones'], examples:['Comparar dos cortes de inventario.','Revisar qué cambió entre dos versiones de un archivo de código.'], related:['inspect','clean','drop'] },
  { id:'clean', name:'Clean', category:'data', summary:'Menos ruido en tus Excel y CSV.', purpose:'Preparar archivos tabulares antes de analizarlos o importarlos en otro sistema.', features:['Trim, duplicados y filas vacías','Headers y normalización de valores','Excel ↔ CSV y columnas problemáticas'], examples:['Quitar espacios alrededor de números de parte.','Normalizar headers y exportar un CSV limpio.'], related:['inspect','diff','drop'] },
  { id:'sql', name:'SQL Lab', category:'data', summary:'Pregúntale a tus archivos con SQL.', purpose:'Analizar datasets localmente con SQLite o DuckDB WASM, sin montar un servidor.', features:['Importar CSV y Excel','SELECT, GROUP BY, JOIN y filtros','Exportar resultados de consultas'], examples:['SELECT localidad, SUM(cantidad) FROM inventario GROUP BY localidad;','Cruzar dos archivos por número de parte.'], related:['inspect','clean','drop'] },
  { id:'context', name:'Context', category:'development', daily:true, summary:'Todo el proyecto, listo para otra IA.', purpose:'Convertir un repo ZIP, README y archivos de código en un paquete de contexto para continuar un proyecto con una IA.', features:['Estructura, README, package.json y archivos importantes','TODO, reglas, arquitectura y decisiones','Últimos cambios proporcionados y prompt para continuar'], examples:['Preparar “PROMPT PARA CONTINUAR PROYECTO” con objetivo, restricciones y archivos.','Compartir un repo sin pegar decenas de archivos manualmente.'], related:['prompt','code','shot'] },
  { id:'prompt', name:'Prompt', category:'development', summary:'Un objetivo claro. Un prompt completo.', purpose:'Preparar instrucciones de desarrollo con el contexto que necesita el siguiente agente.', features:['Presets Feature, Bugfix, UI, Refactor e Investigate','Modos Production y Performance','Repo, rama, objetivo, restricciones, archivos, tests, build, commit y push'], examples:['Pedir un bugfix en main conservando funciones y ejecutando check/build.','Preparar una mejora visual con archivos y restricciones definidos.'], related:['context','projects','code'] },
  { id:'json', name:'JSON Lab', category:'development', summary:'Valida, ordena y transforma JSON.', purpose:'Revisar y preparar datos JSON sin abrir un editor o escribir una conversión manual.', features:['Validación, formato y minificación','Ordenar keys y buscar paths','JSON ↔ CSV y comparación de JSON'], examples:['Encontrar un error de sintaxis en una respuesta JSON.','Convertir una lista de objetos a CSV.'], related:['api','diff','inspect'] },
  { id:'api', name:'API Lab', category:'development', summary:'Una petición rápida, sin abrir Postman.', purpose:'Preparar y ejecutar peticiones HTTP desde una interfaz pequeña en el navegador.', features:['GET, POST, PUT, PATCH y DELETE','Headers, cuerpo JSON e historial','Respuesta legible y copiar cURL'], examples:['Probar un endpoint GET y revisar su respuesta.','Preparar headers y JSON para una petición POST.'], note:'Al implementarse, las peticiones desde navegador dependerán de los permisos CORS del servidor. No podrán saltarse esas restricciones.', related:['json','encode','errors'] },
  { id:'regex', name:'Regex', category:'development', summary:'Comprueba el patrón antes de usarlo.', purpose:'Probar expresiones regulares con coincidencias resaltadas y ejemplos visuales.', features:['Matches, grupos y resaltado','Reemplazo con vista del resultado','Presets para patrones frecuentes'], examples:['Encontrar números de parte dentro de un archivo TXT.','Probar una expresión para limpiar espacios repetidos.'], related:['code','clean','snippets'] },
  { id:'code', name:'Code Lab', category:'development', summary:'Código listo para copiar o compartir.', purpose:'Preparar fragmentos de código, incluidos bloques grandes, sin perder su contenido.', features:['Detectar lenguaje y dar formato','Contar líneas, minificar y quitar comentarios','Copiar y descargar TXT'], examples:['Guardar un bloque largo como TXT para compartirlo.','Dar formato a JavaScript antes de pegarlo en el proyecto.'], related:['context','prompt','drop'] },
  { id:'image', name:'Image Lab', category:'files', summary:'Ajusta una imagen y sigue trabajando.', purpose:'Preparar fotos e imágenes para documentación, páginas y archivos de trabajo.', features:['Resize, crop, rotar y comprimir','Conversión WebP, PNG y JPG','Metadata y portapapeles'], examples:['Reducir el tamaño de una imagen para una página.','Recortar una foto y descargarla en WebP.'], related:['shot','pdf','drop'] },
  { id:'audio', name:'Audio Lab', category:'files', ready:true, summary:'Limpia una grabación y déjala lista para Transcribe.', purpose:'Rescatar audio hablado de juntas largas localmente, conservar el mapa original y enviar WAV a Transcribe.', features:['Silero VAD y RNNoise locales por bloques','Nivelado de voz, silencios con contexto y limitador','WAV, mapa original y envío directo a Transcribe'], examples:['Subir el volumen de una junta grabada muy bajo.','Recortar una grabación y abrir su resultado en Transcribe.'], related:['transcribe','drop'] },
  { id:'pdf', name:'PDF Lab', category:'files', summary:'Las páginas que necesitas, en orden.', purpose:'Preparar documentos PDF para entregas, revisión y archivo.', features:['Unir, dividir, rotar y ordenar páginas','Imágenes → PDF y PDF → imágenes','Extracción de texto'], examples:['Unir varios documentos para una entrega universitaria.','Separar las páginas importantes de un PDF.'], related:['image','transcribe','drop'] },
  { id:'shot', name:'Shot', category:'files', summary:'Una captura que explica el problema.', purpose:'Pegar un screenshot con Ctrl+V y anotarlo para documentar bugs visuales.', features:['Flechas, rectángulos, texto y numeración','Blur y crop','Pegado desde portapapeles y descarga'], examples:['Marcar el botón que falla y numerar los pasos de un bug.','Ocultar un dato sensible antes de compartir una captura.'], related:['image','transcribe','context'] },
  { id:'encode', name:'Encode', category:'utilities', summary:'Codifica, decodifica y verifica.', purpose:'Resolver conversiones técnicas pequeñas sin escribir scripts de un solo uso.', features:['Base64, URL encode/decode y HEX','SHA-256 y hashes de archivo','UUID y Unix timestamp'], examples:['Verificar que dos archivos tienen el mismo SHA-256.','Decodificar Base64 o generar un UUID.'], related:['api','json','convert'] },
  { id:'qr', name:'QR', category:'utilities', summary:'De un enlace a un QR. Y de regreso.', purpose:'Crear y leer códigos QR para compartir enlaces, texto o acceso a Wi-Fi.', features:['Texto y URL → QR','Imagen o cámara → texto','QR para redes Wi-Fi'], examples:['Crear un QR para abrir una herramienta en el iPad.','Leer el enlace que contiene un QR recibido en una imagen.'], related:['drop','shot'] },
  { id:'convert', name:'Convert', category:'utilities', summary:'Cambia el formato, conserva la idea.', purpose:'Convertir unidades, valores y texto en el formato que necesitas para seguir trabajando.', features:['Unidades, bytes y timestamps','HEX, RGB y HSL','Mayúsculas/minúsculas, slug, texto y formatos'], examples:['Convertir un tamaño de bytes a MB.','Pasar un color HEX a RGB o preparar un slug.'], related:['encode','image','code'] },
  { id:'errors', name:'Error Vault', category:'personal', summary:'No resuelvas el mismo error dos veces.', purpose:'Guardar problemas y soluciones localmente con IndexedDB cuando se implemente.', features:['Error, solución y proyecto','Tags, fecha y tecnología','Búsqueda en el historial de soluciones'], examples:['Error: Supabase 401 inventory_bom_current. Solución: guardar aquí la causa y el arreglo verificados.','Encontrar la solución que funcionó para un error anterior de Vite.'], related:['api','snippets','projects'] },
  { id:'snippets', name:'Snippets', category:'personal', ready:true, summary:'Comandos útiles, explicados y listos para copiar.', purpose:'Mantener una biblioteca local de fragmentos y comandos que usas de verdad.', features:['Git, PowerShell, npm y SQL','Supabase, Vite y comandos propios','Organización y copia en un toque'], examples:['Copiar los comandos de pull y build de un proyecto.','Guardar una consulta SQL que usas con frecuencia.'], related:['code','errors','projects'] },
  { id:'projects', name:'Projects', category:'personal', summary:'Tus proyectos y accesos, en un lugar.', purpose:'Reunir enlaces y notas de Inventory Reconciler, Fixed Assets Tracker, Imoviral y Reynoso Toolchain.', features:['GitHub, Pages y documentación','Comandos, notas y build','Localhost y servicios relacionados'], examples:['Abrir repo, Pages y notas de Inventory Reconciler.','Encontrar los comandos para levantar Fixed Assets Tracker.'], related:['context','snippets','errors'] },
];
export const dailyOrder = ['drop','transcribe','inspect','diff','context'];
export const statusLabel = tool => tool.ready ? 'LISTO' : 'EN DESARROLLO';
